### ISSUE TITLE
PeriodO

### ISSUE THREAD

**Issue by zoometh** [eamena-project/eamena-arches-dev#12]
EAMENA can become a new authority on [PeriodO](https://perio.do/en/). To do so, we need to:

1.  fix a small number of errors on **Time**
2. create or load **Spatial** coverage
3. create or load **Authorities**

EAMENA could do the reverse of what is shown in this Arches thread: https://community.archesproject.org/t/use-of-periodo-in-arches/1716, by converting its cultural periods and sub-cultural periods into authoritative periods (with associated DOI, ex: Predynastic: [http://n2t.net/ark:/99152/p0cp44786m7](http://n2t.net/ark:/99152/p0cp44786m7))

**Comment by zoometh** [comment]
Currently, there are some issues with the cultural and sub-cultural periods in EAMENA, see: https://github.com/eamena-oxford/eamena-arches-dev/blob/main/data/time/results/cultural_periods.tsv

![](www/periodo-err-unknown.png)

**Comment by zoometh** [comment]
test notifications @zoometh

**Comment by zoometh** [comment]
test @zoometh ?

**Comment by BijanRouhani** [comment]
Test notifications

**Comment by zoometh** [comment]
@BijanRouhani are you receiving notifications?

**Comment by BijanRouhani** [comment]
@zoometh I received the last one, in which I was mentioned, but not the previous comments.

**Comment by zoometh** [comment]
Great.
Tomorrow I will correct the errors in the chronological periods for which I have the information, as Nichole indicates: https://eamena.slack.com/archives/C8CLY0LR4/p1666778005071629

**Comment by zoometh** [comment]
Now the corrections have been done, @ads04r, @yourvick, @BijanRouhani, @nsheldrick, ... we are looking for someone able to compare the (sub)periods we have in the DB (https://github.com/eamena-oxford/eamenaR/blob/main/inst/extdata/cultural_periods.tsv) and the (sub) periods we have in the BU template https://github.com/eamena-oxford/eamena-arches-dev/tree/main/data/bulk#bu-template-file

**Comment by zoometh** [comment]
@yourvick interested?

**Comment by yourvick** [comment]
Yeah sure, was going to ask you about periods anyway!

**Comment by nsheldrick** [comment]
Testing?

**Comment by zoometh** [comment]
@yourvick did a brilliant job checking the BU ↔️ DB with XLSX macros (see attached). I'm going to go through the EAMENA RDM and Postgres to fix some remaining typos (e.g. `Pre-dynastic` _vs_ `Predynastic`), standardise concepts and remove those that are not used. Meanwhile, the Arches community also seems very keen to work with PeriodO: https://community.archesproject.org/t/use-of-periodo-in-arches/1716/11?u=zoometh

[rdm-bu-period-check.xlsx](https://github.com/eamena-oxford/eamena-arches-dev/files/9921111/rdm-bu-period-check.xlsx)
