### ISSUE TITLE
Jordan Masdar

### ISSUE THREAD

**Issue by zoometh** [eamena-project/eamena-arches-dev#2]
Issues & information on **Jordan Masdar** Arches-powered database:
  * username=`"ubuntu"`
  * arches_version=`"origin/stable/5.2."`
  * my_host=`"34.240.60.23"`
  * projet_name=`"jordan_project"`
  
![Petra_AZ_cropped](https://user-images.githubusercontent.com/67924910/151616628-f9c8fe5a-bd64-4ed6-9a85-de5918a27db2.jpg)
A View of Petra, Jordan © Andrea Zerbini

**Comment by zeinab-jordan** [comment]
welcome to Jordan

**Comment by zeinab-jordan** [comment]
Welcome to Jordan

**Comment by zoometh** [comment]
I will have a look on this [eamena-default card](https://github.com/eamena-oxford/eamena-arches-dev/blob/main/training/templates/eamena-default-card.htm) in coming days
