### ISSUE TITLE
Incrementor function doesn't work for Internationalisation

### ISSUE THREAD

**Issue by zoometh** [eamena-project/eamena-arches-dev#26]
The [Incrementor function](https://database.eamena.org/graph/34cfe98e-c2c0-11ea-9026-02e7594ce0a0/function_manager) doesn't create a new EAMENA ID number when the first Add (green button) is done in the Arabic or French localisation of the DB. It will create an ID labeled "undefined": 

-غير محدد
![image](https://github.com/eamena-project/eamena-arches-dev/assets/67924910/16d58ad4-c35a-43a4-abe2-0d5f0d7bfa58)

- Indefini
![image](https://github.com/eamena-project/eamena-arches-dev/assets/67924910/4ba0cc0f-5841-4ea6-ad52-f4b24811d359)

This error is linked with the issue #27 , https://github.com/eamena-project/eamena-arches-dev/issues/30

**Comment by zoometh** [comment]
It seems to be only a display problem during recording of an HP but not once registration is validated

**Comment by ads04r** [comment]
I *believe* I've now fixed this. Or at least, I have as I understand it. The Incrementor function was generating an i18n string, as it is supposed to, but it was only in English. I assumed (wrongly) that the new resource screen would spot this and just use the English string where none exists in other languages, as all other parts of Arches do. However, this wasn't happening.

I've replaced a small chunk of code in the incrementor.py file for one that generates an i18n explicitly containing an identical "EAMENA-xxxx" string for every activated language (as defined in settings.py). This stops the 'undefined' string from appearing, although we now have a left-to-right string as a default label in a right-to-left language (Arabic) so I'd be grateful if someone who speaks Arabic could try to create a heritage place in that language and let me know if it's acceptable or not.

The new version of the function is on the live database now, but can be rolled back easily if there is a problem. If it's OK then I'll push to the github repo.

**Comment by zoometh** [comment]
>  I'd be grateful if someone who speaks Arabic could try to create a heritage place in that language and let me know if it's acceptable or not
I'll ask one of our colleagues

**Comment by michaeltfisher** [comment]
So, there is updated code for the incrementor function from Farallon. Let me know if you want it, or if yours is working now.

Best,
-Mike


---
Dr. Michael Fisher
Group Leader of Digital Archaeology
Department of Archaeology
Max Planck Institute of Geoanthropology
Kahlaische Straße 10
07745 Jena, Germany
+49 3641 686779

On Jul 18, 2023, at 10:44 AM, Thomas Huet ***@***.***> wrote:



I'd be grateful if someone who speaks Arabic could try to create a heritage place in that language and let me know if it's acceptable or not

I'll ask one of our colleagues

**Comment by zoometh** [comment]
@nsheldrick says it works now.
