### ISSUE TITLE
Bulk-Uploader accepts unstructured bulk (validate and upload)

### ISSUE THREAD

**Issue by zoometh** [eamena-project/eamena-arches-dev#28]
An unstructured XLSX file like [this one](https://github.com/eamena-project/eamena-arches-dev/blob/main/data/bulk/bu/temp.xlsx) will be 'Validate' and successfully uploaded (the message says) even this file's data are completely random

**Comment by ads04r** [comment]
Fixed - I added a short check for valid data in the validation function of the bulk uploader. The bulk uploader does its best to import as much as it can from the file given, but now if the validator finds no valid data at all, it will trigger a warning (which will cause the web UI to refuse to validate, as it always runs in strict mode).
