### ISSUE TITLE
Some 500 HPs deleted during a BU append

### ISSUE THREAD

**Issue by zoometh** [eamena-project/eamena-arches-dev#42]
Running this BU append
```
python manage.py packages -o import_business_data -s ../data_temp/bu_append_hp_grid_20240116.csv -ow append -c "../data_temp/Heritage Place.mapping"
```
Most of the HP listed in [bu_append_hp_grid_20240116.csv](https://github.com/eamena-project/eamena-arches-dev/blob/main/data/bulk/append/bu_append_hp_grid_20240116.csv) have been deleted from the DB at 16:00 UK time, the 2023-01-16.

![image](https://github.com/eamena-project/eamena-arches-dev/assets/67924910/0150ba0d-277b-4716-bc60-b6776cf0b402)

UUID <-> EAMENA IDs are listed [here](https://github.com/eamena-project/eamena-arches-dev/blob/main/data/bulk/append/hp_missing_gs.tsv)

During the process, I had these warnings for these deleted HP :
```
Tue Jan 16 06:28:22 2024 WARNING: 2024-01-16 08:28:18.369285: WARNING: failed to save document in resource: 4dedcdfa-7938-46fc-9bb8-a75cb297ec68 on line 551
```

The tail of the `resource_import.log` file is [here](https://github.com/eamena-project/eamena-arches-dev/blob/main/data/bulk/append/resource_import_log_tail1000_230116.txt)

--- 

**Expected fix**

* restore the entire DB from yesterday (2024-01-15) backup

**Comment by ads04r** [comment]
Database restored, currently re-indexing.
Also, I documented everything in case someone needs to do this when I'm on holiday or something...

https://github.com/eamena-project/eamena-arches-dev/blob/main/dbs/database.eamena/install/notes/Restoring%20DB%20from%20backup.md

**Comment by zoometh** [comment]
To give a bit of context about this "BU append" issue:

Some **255 HPs** had misspelling in the name of the GS they belonged too. The overall idea was to calculate the correct GS by a spatial request (`within`). I removed these values in the GS field using the [bad_grids](https://github.com/eamena-project/eamena-arches-dev/blob/main/data/in-out/out_bad_grids_2.tsv) listing. During this process, me and @yourvick gently slipped from this update to HP with no Grids (which is slightly different) see [this SQL statement](https://github.com/eamena-project/eamena-arches-dev/tree/main/dbs/database.eamena/queries#hp-without-gs) and now find **555 HPs**. Then I tried to BU append Grid ID on these **555 HPs** but it deleted them (see my [Arches forum thread](https://community.archesproject.org/t/import-business-data-ow-append-delete-resources/2218)).

--- 

Related GitHub issues on [duplicates](https://github.com/eamena-project/eamena-arches-dev/issues/42) and [Grid ID typos](https://github.com/eamena-project/eamena-arches-dev/issues/41)

**Comment by zoometh** [comment]
Closed
